DROP TABLE IF exists stats;

CREATE TABLE IF NOT EXISTS STATS (
	id	bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	app varchar(255) NOT NULL,
	uri varchar(255) NOT NULL,
	ip varchar(255) NOT NULL,
	created timestamp without time zone
);

