version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    image: stat_server
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres


  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STAT_SERVICE_URL=http://stats-server:9090



  ewm-db:
    image: postgres:14-alpine
    container_name: explorewithmedb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres